src/Entity/Contact.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactRepository")
 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer", length=255)
     */
    private $numero;

    /**
     * @ORM\Column(type="text", length=255)
     */
    private $message;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

}

templates/components/_footer.html.twig
<footer id="footer" class="top-space">
    <div class="footer1">
        <div class="container">
            <div class="row">
                <div class="col-md-3 widget">
                    <h3 class="widget-title">Contact</h3>
                    <div class="widget-body">
                        <p>+ 33(0)643563213<br>
                            <a href="mailto:#">contact@ineed.com</a><br>
                            <br>
                            17 Rue Albert Thomas, 78130 Les Mureaux
                        </p>
                    </div>
                </div>
                <div class="col-md-3 widget">
                    <h3 class="widget-title">Suivez-nous</h3>
                    <div class="widget-body">
                        <p class="follow-me-icons">
                            <a href=""><i class="fa fa-twitter fa-2"></i></a>
                            <a href=""><i class="fa fa-dribbble fa-2"></i></a>
                            <a href=""><i class="fa fa-github fa-2"></i></a>
                            <a href=""><i class="fa fa-facebook fa-2"></i></a>
                        </p>
                    </div>
                </div>
                <div class="col-md-6 widget">
                    <h3 class="widget-title">
                        Recevoir nos conseils et bonnes pratique une fois pas mois dans votre boite mail
                    </h3>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Adresse Email</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        <small id="emailHelp" class="form-text text-muted">Nous ne partagerons jamais votre email avec qui que ce soit.</small>
                    </div>
                    <div class="widget-body">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer2">
        <div class="container">
            <div class="row">
                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="simplenav">
                            <a href="{{ path('home') }}">Accueil</a> |
                            <a href="{{ path('annonce_new') }}">Annonces</a> |
                            <a href="{{ path('page_contact') }}">Contact</a> |
                            <b><a href="{{ path('membre_inscription') }}">Inscription</a></b>
                        </p>
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="text-right">
                            © Copyright 2019. Tous droits réservés.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</footer>

templates/components/_map.html.twig
    <style>
        /* Always set the map height explicitly to define the size of the div
 * element that contains the map. */
        #map
        {

            position: relative;
            overflow: hidden;
            height: 400px;

        }

        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 50%;
            margin: 0;
            padding: 0;
        }
    </style>

<span class="metadata-marker" style="display: none;" data-region_tag="css"></span>
<span class="metadata-marker" style="display: none;" data-region_tag="html-body"></span>
<span class="metadata-marker" style="display: none;" data-region_tag="script-body"></span>
<div id="map"></div>
<script>

    var map, infoWindow;
    function  initMap () {
        map = new google.maps.Map (document.getElementById ("map"), {

        });
        infoWindow = new google.maps.InfoWindow;

        var uluru = {lat:48.983253, lng:1.925368};

        var map = new google.maps.Map(
            document.getElementById('map'), {zoom: 15, center: uluru});

        var marker = new google.maps.Marker({position: uluru, map: map});

        if (navigator.geolocation)
        {
            navigator.geolocation.getCurrentPosition (function (position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                infoWindow.setPosition (pos);
                infoWindow.setContent ('Lieu trouvé.');
                infoWindow.open (Map);
                map.setCenter (pos);
            },  function() {
                handleLocationError (true, infoWindow, map.getCenter ());
            })
        }
        else {
            // Le navigateur ne supporte pas la géolocalisation
            handleLocationError (false, infoWindow, map.getCenter ());
        }
    }

    function handleLocationError (browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition (pos);
        infoWindow.setContent (browserHasGeolocation?
            "Erreur: le service de géolocalisation a échoué." :
            'Erreur: votre navigateur ne supporte pas la géolocalisation.');
        infoWindow.open (Map );
    }

</script>

templates/components/_nav.html.twig
<div class="navbar navbar-inverse navbar-fixed-top headroom">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span
                        class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
            <a class="navbar-brand" href="{{ path('home') }}"><img src="{{ asset('images/annonces/logo1.png') }}" id="img" width="30%"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li class="active"><a href="{{ path('home') }}">Accueil</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Nos Annonces<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        {% for cat in categories %}
                            <li><a href="{{ path('front_categorie', {
                                    slug : cat.slug
                                }) }}">{{ cat.nom }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{{ path('page_contact') }}">Contact</a></li>
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <li><a class="btn" href="{{ path('annonce_new') }}">D&Eacute;POSER UNE ANNONCE</a></li>
                    <li><a class="btn" href="{{ path('security_deconnexion') }}">Deconnexion</a></li>
                {% else %}
                    <li><a class="btn" href="{{ path('membre_inscription') }}">INSCRIPTION / CONNEXION</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>